Repository FRONTENDBOOTCAMP-14th/Sashimi, pull requests merged in 2025-05, with the labels that each got.

#33 login - 접근성 관련 기능 추가, css 코드 리팩토링
  src/components/account/login.css
  src/components/account/login.html
Labels: ♿️ accessibility, ♻️ refactor

#34 header - 불필요한 코드 제거, aria-label 추가
  src/components/header/header.css
  src/components/header/header.html
Labels: ♿️ accessibility, 💅 style

#40 login - 컴포넌트 레이아웃 css적용, css 리팩토링
  src/components/account/login.css
  src/components/account/login.html
Labels: ♻️ refactor, 🎨 design

#42 [style 및 design] header 이미지 경로 수정, footer 컴포넌트 마크업 및 스타일링 작성
  src/components/footer/footer.css
  src/components/footer/footer.html
  src/components/header/header.css
  src/components/header/header.html
Labels: 💅 style, 🎨 design

#44 search - 컴포넌트 마크업 및 스타일링
  index.html
  public/icon/icon-big-x.svg
  public/icon/icon-search.svg
  src/components/search/search.css
  src/components/search/search.html
Labels: ♿️ accessibility, ✨ feature, ♻️ refactor, 🎨 design

#45 profiles - 컴포넌트 마크업 및 스타일링
  public/icon/profiles-edit.svg
  public/icon/profiles-lock.svg
  public/images/profiles-profile-1.png
  public/images/profiles-profile-2.png
  public/images/profiles-profile-3.png
  public/images/profiles-profile-4.png
  src/components/landing-page/landing-page.css
  src/components/landing-page/landing-page.html
  src/components/profiles/profiles.css
  src/components/profiles/profiles.html
Labels: ♿️ accessibility, ✨ feature, 🎨 design

#47 [style 및 design] 크로스브라우징 하면서 발견된 오류들 수정
  src/components/footer/footer.css
  src/components/footer/footer.html
  src/components/header/header.css
Labels: 💅 style, 🎨 design
